<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.81.0" />


<title>Can you predict a Cinderella team? - Peyton Kort Blog</title>
<meta property="og:title" content="Can you predict a Cinderella team? - Peyton Kort Blog">


  <link href='/favicon.ico' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/rstudio/blogdown">GitHub</a></li>
    
    <li><a href="https://twitter.com/pkort73">Twitter</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">8 min read</span>
    

    <h1 class="article-title">Can you predict a Cinderella team?</h1>

    
    <span class="article-date">2021-04-02</span>
    

    <div class="article-content">
      
<script src="/2021/04/02/can-you-predict-a-cinderella-team/index_files/header-attrs/header-attrs.js"></script>
<script src="/2021/04/02/can-you-predict-a-cinderella-team/index_files/kePrint/kePrint.js"></script>
<link href="/2021/04/02/can-you-predict-a-cinderella-team/index_files/lightable/lightable.css" rel="stylesheet" />


<p>Teams like VCU and UCLA have had incredible runs in March. Back in 2011, VCU made it all the way to the Final Four as an 11 seed. UCLA has made that exact same run as an 11 seed this year.</p>
<p>But what do these two teams have in common. Both were teams that had to play in the First Four, which are the lowest at-large teams facing off against each other. There are a total of four of the lowest at-large teams each year. The First Four started in 2011, in which two 11 seeded teams match up, and two 16 seeded teams match up (making it a total of four games). Only two of these First Four teams have made it past the Sweet 16. They are the 2011 VCU Rams and the 2021 UCLA Bruins.</p>
<p>Let’s compare these two teams stats throughout the seasons of there historic runs.</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.3     ✓ purrr   0.3.4
## ✓ tibble  3.0.5     ✓ dplyr   1.0.5
## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
## ✓ readr   1.4.0     ✓ forcats 0.5.1</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(ggrepel)
library(scales)</code></pre>
<pre><code>## 
## Attaching package: &#39;scales&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     discard</code></pre>
<pre><code>## The following object is masked from &#39;package:readr&#39;:
## 
##     col_factor</code></pre>
<pre class="r"><code>library(kableExtra)</code></pre>
<pre><code>## 
## Attaching package: &#39;kableExtra&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     group_rows</code></pre>
<pre class="r"><code>library(formattable)</code></pre>
<pre><code>## 
## Attaching package: &#39;formattable&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:scales&#39;:
## 
##     comma, percent, scientific</code></pre>
<pre class="r"><code>library(readr)
library(dplyr)</code></pre>
<p>The statistics I am working with are from the 2010/2011 NCAA College Basketball season and 2020/2021 NCAA College Basketball season. All this data is from Sports Reference. Also I made my own data set from Google Sheets that just has VCU’s 2010/2011 season and UCLA in the 2020/2021 season.</p>
<pre class="r"><code>vcuyear &lt;- read_csv(&quot;~/Desktop/SPMC_350_Spring_2021/2021_spring_sports_data_analysis/data/2010_2011_teamstats.csv&quot;)</code></pre>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   .default = col_double(),
##   School = col_character()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<pre class="r"><code>thisyear &lt;- read_csv(&quot;~/Desktop/SPMC_350_Spring_2021/2021_spring_sports_data_analysis/data/2020_2021_teamstats.csv&quot;)</code></pre>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   .default = col_double(),
##   School = col_character()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<pre class="r"><code>uclawithvcu &lt;- read_csv(&quot;~/Desktop/SPMC_350_Spring_2021/2021_spring_sports_data_analysis/data/ucla_vcu_data.csv&quot;)</code></pre>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   .default = col_double(),
##   Year = col_character(),
##   School = col_character()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<p>What I want to figure out is whether I could predict a Cinderella Team solely based off stats. There have only been four teams that are 11 seeded or lower to make it to the Final Four (2006 George Mason, 2011 VCU, 2018 Loyola, 2021 UCLA). I decided to choose VCU and UCLA to compare stats because they were both in the First Four and it’s so crazy that a team that barely even made it in the NCAA Tournament got all the way to the Final Four. So let’s compare the stats.</p>
<pre class="r"><code>thisyear &lt;- thisyear %&gt;%
  separate(School, into=c(&quot;School&quot;, &quot;Tournament&quot;), sep=&quot;NCAA&quot;) %&gt;%
  arrange(Rk)</code></pre>
<pre><code>## Warning: Expected 2 pieces. Missing pieces filled with `NA` in 287 rows [2, 3,
## 4, 5, 6, 8, 9, 10, 12, 13, 14, 15, 16, 18, 19, 20, 21, 23, 24, 25, ...].</code></pre>
<pre class="r"><code>vcuyear &lt;- vcuyear %&gt;%
  separate(School, into=c(&quot;School&quot;, &quot;Tournament&quot;), sep=&quot;NCAA&quot;) %&gt;%
  arrange(Rk)</code></pre>
<pre><code>## Warning: Expected 2 pieces. Missing pieces filled with `NA` in 277 rows [1, 3,
## 6, 7, 8, 9, 10, 11, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25, 26, ...].</code></pre>
<pre class="r"><code>vcu &lt;- vcuyear %&gt;% 
  filter(Rk == &quot;322&quot;)

ucla &lt;- thisyear %&gt;%
  filter(Rk == &quot;325&quot;)</code></pre>
<p>For these next few codes I mutated some new rows. I added 5 new rows for 2020/2021 and 2010/2011 data set. Then I added 15 new rows of data for my data of just VCU and UCLA. The rows I added were stats like points per game, opponent points per game, margin of victory, assist to turnover ratio, 3 pointers attempted per game, 3 pointers made per game, all stats I think that are important to helping a team win.</p>
<pre class="r"><code>thisyear &lt;- thisyear %&gt;%
  mutate(AssistTurnoverRatio = (AST)/TOV) %&gt;% 
  mutate(PointsPG = (`Total Points`)/G) %&gt;%
  mutate(OppPointsPG = (`Opponent Points`)/G) %&gt;%
  mutate(Margin = PointsPG - OppPointsPG) %&gt;%
  mutate(`3PointersAttemptedPG` = (`3PA`)/G)</code></pre>
<pre class="r"><code>vcuyear &lt;- vcuyear %&gt;%
  mutate(AssistTurnoverRatio = (AST)/TOV) %&gt;% 
  mutate(PointsPG = (`Total Points`)/G) %&gt;%
  mutate(OppPointsPG = (`Opponent Points`)/G) %&gt;%
  mutate(Margin = PointsPG - OppPointsPG) %&gt;%
  mutate(`3PointersAttemptedPG` = (`3PA`)/G)</code></pre>
<pre class="r"><code>ucla &lt;- ucla %&gt;%
  mutate(AssistTurnoverRatio = (AST)/TOV) %&gt;% 
  mutate(PointsPG = (`Total Points`)/G) %&gt;%
  mutate(OppPointsPG = (`Opponent Points`)/G) %&gt;%
  mutate(Margin = PointsPG - OppPointsPG) %&gt;% 
  mutate(`3PointersAttemptedPG` = (`3PA`)/G)</code></pre>
<pre class="r"><code>vcu &lt;- vcu %&gt;%
  mutate(AssistTurnoverRatio = (AST)/TOV) %&gt;% 
  mutate(PointsPG = (`Total Points`)/G) %&gt;%
  mutate(OppPointsPG = (`Opponent Points`)/G) %&gt;%
  mutate(Margin = PointsPG - OppPointsPG) %&gt;% 
  mutate(`3PointersAttemptedPG` = (`3PA`)/G)</code></pre>
<pre class="r"><code>uclawithvcu &lt;- uclawithvcu %&gt;%
  mutate(AssistTurnoverRatio = (AST)/TOV) %&gt;% 
  mutate(PointsPG = (`Total Points`)/G) %&gt;%
  mutate(OppPointsPG = (`Opponent Points`)/G) %&gt;%
  mutate(Margin = PointsPG - OppPointsPG) %&gt;% 
  mutate(`3PointersAttemptedPG` = (`3PA`)/G) %&gt;%
  mutate(FTPG  = (FT)/G) %&gt;%
  mutate(FTAPG = (FTA)/G) %&gt;%
  mutate(ORBPG = (ORB)/G) %&gt;%
  mutate(TRBPG = (TRB)/G) %&gt;%
  mutate(ASTPG = (AST)/G) %&gt;%
  mutate(STLPG = (STL)/G) %&gt;%
  mutate(BLKPG = (BLK)/G) %&gt;%
  mutate(TOVPG = (TOV)/G) %&gt;%
  mutate(PFPG = (PF)/G) %&gt;%
  mutate(`3PointerMadePG` = (`3P`)/G)</code></pre>
<pre class="r"><code>vcuwithucla &lt;- uclawithvcu %&gt;%
  select(Year, School, G, W, L, `W-L%`, SRS, SOS, `Conference W`, `Conference L`, `Home W`, `Home L`, `Away W`, `Away L`, PointsPG, OppPointsPG, Margin, `FG%`, `3PointerMadePG`, `3PointersAttemptedPG`, `3P%`, FTPG, FTAPG, `FT%`, TRBPG, ORBPG, ASTPG, STLPG, BLKPG, TOVPG, PFPG, AssistTurnoverRatio) %&gt;% 
  pivot_longer(cols = G:AssistTurnoverRatio, names_to = &quot;Statistic&quot;, values_to = &quot;Result&quot;) %&gt;% 
 select(-Year) %&gt;% 
  pivot_wider(names_from = School, values_from = Result)</code></pre>
<p>I set up the VCU and UCLA data into a table chart. This table chart does a great job of showing every stat for UCLA and VCU. You can see what they have in common and what they don’t.</p>
<pre class="r"><code>tablemajor &lt;- vcuwithucla %&gt;%
  ungroup()</code></pre>
<pre class="r"><code>tablemajor %&gt;% kable() %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;condensed&quot;)) %&gt;% 
  column_spec(2, bold = T, color = &quot;white&quot;, background = &quot;Black&quot;) %&gt;%
  column_spec(3, bold = T, color = &quot;white&quot;, background = &quot;Blue&quot;)</code></pre>
<table class="table table-striped table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Statistic
</th>
<th style="text-align:right;">
VCU
</th>
<th style="text-align:right;">
UCLA
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
G
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
40.000000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
31.000000
</td>
</tr>
<tr>
<td style="text-align:left;">
W
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
28.000000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
22.000000
</td>
</tr>
<tr>
<td style="text-align:left;">
L
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
12.000000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
9.000000
</td>
</tr>
<tr>
<td style="text-align:left;">
W-L%
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
0.700000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
0.710000
</td>
</tr>
<tr>
<td style="text-align:left;">
SRS
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
8.560000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
16.070000
</td>
</tr>
<tr>
<td style="text-align:left;">
SOS
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
3.780000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
10.850000
</td>
</tr>
<tr>
<td style="text-align:left;">
Conference W
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
12.000000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
13.000000
</td>
</tr>
<tr>
<td style="text-align:left;">
Conference L
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
6.000000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
6.000000
</td>
</tr>
<tr>
<td style="text-align:left;">
Home W
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
11.000000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
11.000000
</td>
</tr>
<tr>
<td style="text-align:left;">
Home L
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
3.000000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
1.000000
</td>
</tr>
<tr>
<td style="text-align:left;">
Away W
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
8.000000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
5.000000
</td>
</tr>
<tr>
<td style="text-align:left;">
Away L
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
6.000000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
6.000000
</td>
</tr>
<tr>
<td style="text-align:left;">
PointsPG
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
71.600000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
72.870968
</td>
</tr>
<tr>
<td style="text-align:left;">
OppPointsPG
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
66.825000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
67.645161
</td>
</tr>
<tr>
<td style="text-align:left;">
Margin
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
4.775000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
5.225807
</td>
</tr>
<tr>
<td style="text-align:left;">
FG%
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
0.434000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
0.458000
</td>
</tr>
<tr>
<td style="text-align:left;">
3PointerMadePG
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
8.475000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
6.774193
</td>
</tr>
<tr>
<td style="text-align:left;">
3PointersAttemptedPG
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
22.925000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
18.354839
</td>
</tr>
<tr>
<td style="text-align:left;">
3P%
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
0.370000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
0.369000
</td>
</tr>
<tr>
<td style="text-align:left;">
FTPG
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
14.725000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
13.064516
</td>
</tr>
<tr>
<td style="text-align:left;">
FTAPG
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
20.600000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
18.225807
</td>
</tr>
<tr>
<td style="text-align:left;">
FT%
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
0.715000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
0.717000
</td>
</tr>
<tr>
<td style="text-align:left;">
TRBPG
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
32.300000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
35.000000
</td>
</tr>
<tr>
<td style="text-align:left;">
ORBPG
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
10.700000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
9.838710
</td>
</tr>
<tr>
<td style="text-align:left;">
ASTPG
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
14.575000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
13.419355
</td>
</tr>
<tr>
<td style="text-align:left;">
STLPG
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
8.200000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
4.967742
</td>
</tr>
<tr>
<td style="text-align:left;">
BLKPG
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
3.500000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
2.838710
</td>
</tr>
<tr>
<td style="text-align:left;">
TOVPG
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
11.300000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
10.516129
</td>
</tr>
<tr>
<td style="text-align:left;">
PFPG
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
18.375000
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
16.064516
</td>
</tr>
<tr>
<td style="text-align:left;">
AssistTurnoverRatio
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Black !important;">
1.289823
</td>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: Blue !important;">
1.276074
</td>
</tr>
</tbody>
</table>
<p>As you can see, UCLA had a way tougher schedule than VCU, due to the tougher conference that UCLA plays in (Pac 12 vs. A-10). This would also make there SRS way higher than VCU’s. You can also see that the conference records for both teams were very similar.</p>
<p>VCU and UCLA had very similar points per game and opponent points per game, which made the margin also very similar. There free throw percentages were nearly the exact same at 71.5% and 71.7%. Lastly the assist to turnover ratio was also nearly spot on at 1.289 for VCU and 1.276 for UCLA.</p>
<p>Neither VCU nor UCLA were any where near the top of the nation in any given stat. Two stats that were the most similar was the average margin of victory (4.8 and 5.2) and assist to turnover ratio (1.289 and 1.276). So I decided to make a scatter plot comparing them to the nation in those two stats.</p>
<pre class="r"><code>ggplot(thisyear, aes(x=AssistTurnoverRatio, y=Margin)) + 
  geom_point() + 
  geom_point(data = thisyear, aes(x=AssistTurnoverRatio, y=Margin), color = &quot;Gray&quot;) + 
  geom_point(data = ucla, aes(x=AssistTurnoverRatio, y=Margin), color = &quot;Blue&quot;) + 
  labs(title= &quot;UCLA compared to every NCAA team in 2021&quot;, subtitle = &quot;UCLA toward the middle of the nation&quot;, x = &quot;Assist to Turnover Ratio in 2021 Season&quot;, y = &quot;Average margin of victory&quot;, caption = &quot;Source: Sports-Reference.com | By Peyton Kort&quot;) + 
  theme_minimal() + 
  theme(
    plot.title = element_text(size = 16, face = &quot;bold&quot;),
    axis.title = element_text(size = 12), 
    plot.subtitle = element_text(size=10), 
    panel.grid.minor = element_blank()
    ) + 
   geom_text_repel(
    data=ucla, 
    aes(x=AssistTurnoverRatio, y=Margin, label=School)
  )</code></pre>
<pre><code>## Warning: Removed 8 rows containing missing values (geom_point).

## Warning: Removed 8 rows containing missing values (geom_point).</code></pre>
<p><img src="/2021/04/02/can-you-predict-a-cinderella-team/index_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<pre class="r"><code>ggplot(vcuyear, aes(x=AssistTurnoverRatio, y=Margin)) + 
  geom_point() + 
  geom_point(data = vcuyear, aes(x=AssistTurnoverRatio, y=Margin), color = &quot;Gray&quot;) + 
  geom_point(data = vcu, aes(x=AssistTurnoverRatio, y=Margin), color = &quot;Black&quot;) + 
  labs(title = &quot;VCU compared to every NCAA team in 2011&quot;, subtitle = &quot;VCU more toward the top than UCLA was&quot;, x = &quot;Assist to Turnover Ratio in 2011 Season&quot;, y = &quot;Average margin of victory&quot;, caption = &quot;Source: Sports-Reference.com | By Peyton Kort&quot;) + 
  theme_minimal() + 
  geom_text_repel(
    data=vcu, 
    aes(x=AssistTurnoverRatio, y=Margin, label=School)) + 
  theme(
    plot.title = element_text(size = 16, face = &quot;bold&quot;),
    axis.title = element_text(size = 12), 
    plot.subtitle = element_text(size=10), 
    panel.grid.minor = element_blank()
  )</code></pre>
<p><img src="/2021/04/02/can-you-predict-a-cinderella-team/index_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Both VCU and UCLA were around the middle of the nation in the scatter plot. They were however above average in each category. VCU was a little more near the top then UCLA was.</p>
<p>Everyone wants to think there is some secret formula to predict a Cinderella run in the NCAA Tournament. But sadly, there is no secret. It takes a special team to make a run like this. You never know when a Cinderella run like VCU in 2011, or UCLA this past year, but when it happens you just gotta appreciate it!</p>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    

    
  </body>
</html>

